### ISSUE TITLE
Create a style guide

### ISSUE THREAD

**Issue by RuiApostolo** [EPCCed/epcc-reframe#24]
Having a consistent style guide helps when creating new, or upgrading older tests.
Furthermore, including linter configuration files in the repository would ensure everyone can easily follow the rules.

I am partial to the philosophy behind [Black](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html) - I think it makes for readable code.
Regarding PEP8, I don't like the 79 character limit (E501) and W503, as I feel the first pressures people into writing more cryptic variable names, and the latter is supposed to be reversed soon. I would suggest ignoring W503 and setting a line-length of 120 characters.

**Comment by RuiApostolo** [comment]
# Code style proposal

To follow PEP8 with a few exceptions, based mostly on perceptions on aesthetics of the code.
- [E501](https://www.flake8rules.com/rules/E501.html): The 79 character limit can lead developers to use shortened, cryptic variable names, especially in situations with nested modules, classes, functions, etc.
- [W503](https://www.flake8rules.com/rules/W503.html): Has been mostly deprecated, but some tools still flag it as "bad syntax".

## The following tools and configurations are a way to enforce the rules above:

- Use a code checker:
	- [pylint](https://pypi.org/project/pylint/): a Python static code analysis tool.
	- [flake8](https://flake8.pycqa.org/en/latest/): a tool that glues together `pycodestyle`, `pyflakes`, and `mccabe` to check the style and quality of Python code.
	- [flake8-pyproject](https://pypi.org/project/Flake8-pyproject/): Because flake8 refuses to adopt the use of the `pyproject.toml` file.
	- [vim-flake8](https://github.com/nvie/vim-flake8): a flake8 plugin for Vim.
	- [elpy](https://github.com/jorgenschaefer/elpy): an emacs python plugin that integrates with flake8, black, and others.

- Use an auto-formatter:
	- [black](https://black.readthedocs.io/en/stable/index.html#): An opinionated auto-formatter.

The addition to the repo of a `pyproject.toml` file, with the configuration options for pylint, flake8, and black. It includes the names of the additional "built-ins" defined by reframe, so that syntax checkers don't flag them as "undefined"

## Naming conventions:

Follow the [Python naming conventions](https://peps.python.org/pep-0008/#naming-conventions), in summary:

### Modules
	
Modules should be named all-lowercase, with underscores used where it improves readability.

For applications with more than one test, one module should contain the basic setup for that application, and each test should then be a different module (named for the type of system or test that it performs) that imports the base one.
For example:


```bash
tests/apps/lammps/
	├── dipole_large.py
	├── ethanol.py
	├── lammps.py
	└── src
	    ├── data.ethanol
	    ├── in.ethanol
	    └── in_2048.dipole
```

### Classes

Classes, including Type Variables, should be named using CamelCase.
Classes that define tests should have the application name as prefix, and those that setup the application should have the suffix "Base".
When different classes for CPU/GPU tests are needed, add the corresponding suffix.
Exceptions should include the suffix "Error"

Example:

```python
# grep "class" lammps.py
class LAMMPSBase(rfm.RunOnlyRegressionTest)
(...)

# grep "class" ethanol.py
class LAMMPSEthanol(LAMMPSBase)
(...)
class LAMMPSEthanolCPU(LAMMPSEthanol)
(...)
class LAMMPSETHANOLGPU(LAMMPSEthanol)
``` 

### Methods, functions, and variables

Method, function, and variable names should be lowercase, with words separated by underscores.

Examples:

```python
executable = "lmp"
keep_files = ["log.lammps"]
strict_check = True

def assert_finished(self):
(...)
```

### Constants

Constants should be declared at the module level, and use all-caps with underscores separating words.

Example:

```python
PI = 3.14159265359
```

### Dictionary names and keys

Avoid having a dictionary key share a name with the dictionary or a key in a nested dictionary:

Examples of what to avoid:

```python
performance = {"performance": [1, 0.01, -0.01, "ns/day"]}
extra_resources = {"qos": {"qos": "standard"}}
```

## Docstrings

Modules, classes, and functions should have triple-quote delimited doc-strings with a short explanation of the intent of the module/class/function.
Where applicable, method/function parameter should be listed and have their expected types detailed.

Module example:

```python
"""Base module for LAMMPS tests"""
```

Class example:

```python
"""LAMMPS Ethanol test for performance testing -- CPU nodes"""
```

Function example:

```python
"""
Extracts performance value to compare with reference value.
Returns a float.
"""
```

## Type and Function Annotations

Python 3 introduced Type/Function annotations. They allow anyone to know, at a quick glance, what type a variable, or a function parameter is.
Their use is recommended for functions that return a value, rather than modifying an object, and when declaring an "empty" variable.

For example:

```python
time_limit: str = None
n_nodes: int = None
valid_systems: list[str] = []
env_vars: dict[str, str] = {}
reference: dict[str, dict[str, tuple[float, float, float, str]]]

def extract_energy(self) -> float:
        """Extracts value of system energy for correctness check"""
        return sn.extractsingle(
            r"\s+11000\s+\S+\s+\S+\s+(?P<energy>\S+)",
            self.keep_files[0],
            "energy",
            float,
            item=-1,
        )
```

**Comment by RuiApostolo** [comment]
The following `lint.yaml` seems to find a lot of issues, some tinkering might be needed:

```yaml
name: Linting

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: pylint
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
        ignore: "W503"
        max-line-length: "120"
        path: "tests"
        plugins: "flake8-bugbear flake8-black flake8-pyproject"

  python-black:
    name: Python Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Black
        uses: cytopia/docker-black@0.8
        with:
          path: 'tests/'
```
